openapi: 3.1.1
info:
  title: ElectionService API
  description: API for managing elected positions and user nominations.
  version: 0.1.0

servers:
  - url: http://api.example.com/v1

paths:
  /positions:
    post:
      summary: Create a new position that users can be nominated to.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePositionRequest"
      responses:
        "201":
          description: Position successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Position"
    get:
      summary: Retrieve all open positions available for nominations.
      responses:
        "200":
          description: List of open positions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Position"

  /positions/{id}/close:
    post:
      summary: Close a position to prevent further nominations.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Position successfully closed.
        "404":
          description: Position not found.

  /positions/{id}/nominations:
    post:
      summary: Nominate a user to a position.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNominationRequest"
      responses:
        "201":
          description: Nomination created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nomination"
        "404":
          description: Position not found.
    get:
      summary: Get all nominations submitted for a position.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of nominations for the position.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Nomination"
        "404":
          description: Position not found.

  /positions/{id}/nominations/{username}:
    get:
      summary: Get nomination status for a specific user on a position.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Nomination found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nomination"
        "404":
          description: Nomination not found.

  /positions/{id}/nominations/{username}/accept:
    post:
      summary: Mark a nomination as accepted.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - in: path
          name: username
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Nomination successfully accepted.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nomination"
        "404":
          description: Nomination not found.

components:
  schemas:

    Position:
      type: object
      description: A position that users may be nominated to.
      properties:
        position_id:
          type: integer
        meeting_id:
          type: integer
        position_name:
          type: string
        is_open:
          type: boolean
          description: Whether the position is still accepting nominations.
      required:
        - position_id
        - meeting_id
        - position_name
        - is_open

    CreatePositionRequest:
      type: object
      properties:
        meeting_id:
          type: integer
        position_name:
          type: string
      required:
        - meeting_id
        - position_name

    Nomination:
      type: object
      description: A nomination of a user to a position.
      properties:
        position_id:
          type: integer
        username:
          type: string
        accepted:
          type: boolean
          description: Whether the nomination has been accepted.
      required:
        - position_id
        - username
        - accepted

    CreateNominationRequest:
      type: object
      properties:
        username:
          type: string
      required:
        - username
